name: joura
summary: journalctl log wather and send telegram
description: |
  A simple logging
version: v0.0.1
confinement: devmode
base: core18

architectures:
  - build-on: [arm64, armhf, amd64]

apps:
  joura:
    command: joura

parts:
  joura:
    plugin: go
    source: .
    go-importpath: joura

plugs:
  joura-home:
    interface: home
  joura-network:
    interface: network